"use client";

import { AnimatePresence, motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Clock3, Droplets, ExternalLink, Filter, PackageCheck, ShieldCheck, Snowflake, Truck, X } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { GoogleReviews } from "@/components/ui/GoogleReviews";

const whatsapp = "https://wa.me/6287816777741?text=Halo%20Pools%20Ice,%20saya%20ingin%20order%20es";
const steps = [
  { number: "01", title: "Air yang disiapkan", text: "Air difiltrasi melalui reverse osmosis agar jernih, bersih, dan memiliki rasa yang netral.", icon: Filter },
  { number: "02", title: "Dibekukan perlahan", text: "Proses pembekuan terukur menghasilkan es yang padat, bening, dan tahan lebih lama.", icon: Snowflake },
  { number: "03", title: "Diperiksa sebelum jalan", text: "Setiap batch melewati pemeriksaan sebelum dikemas untuk kebutuhan service Anda.", icon: ShieldCheck },
  { number: "04", title: "Tiba saat dibutuhkan", text: "Pesanan berangkat dari Denpasar dan dikirim mengikuti ritme operasional bisnis Anda.", icon: Truck },
];
const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.6 } } };

export default function Home() {
  const [selectedImage, setSelectedImage] = useState<string | null>(null);

  return <div className="overflow-hidden">
    <section className="relative min-h-[780px] bg-[#1b211e] px-5 pb-20 pt-36 text-[#f2f0e9] md:px-10 lg:min-h-[850px] lg:pt-40">
      <div className="absolute inset-0 opacity-20 [background-image:linear-gradient(90deg,rgba(242,240,233,.12)_1px,transparent_1px),linear-gradient(rgba(242,240,233,.12)_1px,transparent_1px)] [background-size:80px_80px]" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.15fr_.85fr] lg:gap-4">
        <motion.div initial="hidden" animate="visible" variants={reveal}>
          <p className="mb-7 flex items-center gap-3 text-[11px] font-bold uppercase tracking-[0.28em] text-[#8bd7ff]"><span className="h-px w-10 bg-[#8bd7ff]" /> Es untuk bisnis Bali</p>
          <h1 className="max-w-3xl font-heading text-6xl font-medium leading-[.94] tracking-[-.06em] md:text-8xl lg:text-[7.6rem]">Es yang<br /><span className="text-[#8bd7ff]">siap bekerja.</span></h1>
          <p className="mt-8 max-w-md text-base leading-7 text-white/65 md:text-lg">Es bening dan tahan lama untuk membuat minuman, dapur, dan layanan Anda tetap lancar.</p>
          <div className="mt-10 flex flex-wrap items-center gap-4"><Link href={whatsapp} target="_blank" className="inline-flex items-center gap-3 rounded-full bg-[#8bd7ff] px-6 py-4 text-sm font-bold text-[#14202a] transition-transform hover:-translate-y-1">Pesan sekarang <ArrowUpRight className="h-4 w-4" /></Link><a href="#products" className="inline-flex items-center gap-3 px-3 py-4 text-sm font-bold text-white/75 transition-colors hover:text-[#8bd7ff]">Lihat produk <ArrowDownRight className="h-4 w-4" /></a></div>
          <div className="mt-16 grid max-w-lg grid-cols-3 border-t border-white/15 pt-6 text-xs text-white/50"><span><strong className="block font-heading text-2xl text-white">5.0</strong>Penilaian Google</span><span><strong className="block font-heading text-2xl text-white">07–19</strong>Buka tiap hari</span><span><strong className="block font-heading text-2xl text-white">2020</strong>Mulai melayani</span></div>
        </motion.div>
        <motion.div initial={{ opacity: 0, scale: .92, rotate: 2 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ duration: .9, delay: .15 }} className="relative mx-auto aspect-square w-full max-w-[520px] lg:-mr-8"><div className="absolute inset-[8%] rounded-full border border-[#8bd7ff]/40" /><div className="absolute inset-[18%] rounded-full border border-white/15" /><div className="absolute inset-[27%] rounded-full bg-[#f2f0e9] shadow-[0_0_80px_rgba(139,215,255,.18)]" /><div className="absolute inset-[31%] overflow-hidden rounded-full bg-[#dcecf4]"><div className="absolute -left-1/4 top-1/4 h-1/2 w-[150%] rotate-[-20deg] bg-white/75 blur-2xl" /><div className="absolute bottom-8 left-8 h-24 w-24 rounded-full bg-[#8bd7ff]/60 blur-xl" /><Image src="/logo-clear.png" alt="Pools Ice" fill className="object-contain p-14" sizes="(max-width: 768px) 80vw, 420px" priority /></div><span className="absolute right-0 top-1/4 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-[10px] font-bold uppercase tracking-[.2em] text-white/70 backdrop-blur">Bening dan bersih</span><span className="absolute bottom-1/4 left-0 rounded-full border border-[#8bd7ff]/40 bg-[#1b211e]/70 px-4 py-2 text-[10px] font-bold uppercase tracking-[.2em] text-[#8bd7ff] backdrop-blur">Untuk bar dan dapur</span></motion.div>
      </div>
      <div className="absolute bottom-7 left-5 right-5 flex justify-between text-[10px] uppercase tracking-[.22em] text-white/30 md:left-10 md:right-10"><span>Scroll to explore</span><span>Bali / Indonesia</span></div>
    </section>

    <section id="about" className="bg-[#f2f0e9] px-5 py-24 md:px-10 md:py-36"><div className="mx-auto max-w-7xl"><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><div><p className="section-kicker">01 / Standar kami</p><h2 className="mt-5 max-w-xs font-heading text-4xl font-medium leading-tight tracking-[-.04em] md:text-5xl">Hal kecil yang membuat layanan terasa besar.</h2></div><div><p className="max-w-3xl text-2xl leading-[1.25] tracking-[-.02em] text-[#39423b] md:text-4xl">Saat tamu datang, minuman harus terasa pas. Kami membantu Anda menjaga hasil itu, gelas demi gelas.</p><div className="mt-12 grid gap-8 border-t border-[#c9c8bf] pt-8 sm:grid-cols-3"><Info icon={Droplets} title="Bening dan netral" text="Tidak mengubah rasa atau tampilan minuman." /><Info icon={Clock3} title="Tiba tepat waktu" text="Jadwal kirim mengikuti kebutuhan usaha Anda." /><Info icon={PackageCheck} title="Rapi dan siap" text="Dikemas bersih sampai siap disajikan." /></div></div></div></div></section>

    <section id="products" className="bg-[#e6e5dc] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="section-kicker">02 / Pilihan es</p><h2 className="mt-5 max-w-3xl font-heading text-5xl font-medium tracking-[-.05em] md:text-7xl">Pilih dingin yang<br /><span className="text-[#347fa7]">pas untuk kerja Anda.</span></h2></div><p className="max-w-xs text-sm leading-6 text-[#69716b]">Dua bentuk es. Cara pakai yang berbeda. Kualitas yang sama.</p></div><div className="mt-16 grid gap-5 lg:grid-cols-[1.12fr_.88fr]"><ProductCard title="Es Kristal" eyebrow="01 / Untuk gelas" description="Bongkahan padat dan bening untuk kopi, mocktail, cocktail, dan minuman yang ingin tetap terlihat bersih." tone="light" /><ProductCard title="Es Serut" eyebrow="02 / Untuk dapur" description="Tekstur halus untuk dessert, es campur, seafood, dan sajian yang butuh dingin lebih cepat." tone="dark" /></div></div></section>

    <section className="bg-[#dcecf4] px-5 py-20 text-[#1b211e] sm:py-24 md:px-10 md:py-28 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-12 md:grid-cols-[.72fr_1.28fr] md:gap-10 lg:grid-cols-[.8fr_1.2fr] lg:gap-14"><div className="md:sticky md:top-32 md:self-start"><p className="section-kicker text-[#347fa7]">03 / Cara kami bekerja</p><h2 className="mt-5 max-w-sm font-heading text-5xl font-medium leading-[.98] tracking-[-.05em] sm:text-6xl lg:text-7xl">Dibuat dengan sabar.<br />Dikirim dengan pasti.</h2><p className="mt-7 max-w-sm text-sm leading-6 text-[#526a6b]">Es yang baik butuh proses yang rapi, bukan proses yang terburu-buru.</p></div><div className="relative ml-3 pl-8 sm:ml-4 sm:pl-10 md:ml-0 md:pl-11"><motion.div initial={{ scaleY: 0 }} whileInView={{ scaleY: 1 }} viewport={{ once: true, amount: 0.05 }} transition={{ duration: 1.8, ease: "easeInOut" }} className="absolute bottom-0 left-0 top-0 z-0 w-[2px] origin-top bg-[#347fa7]/45" />{steps.map((step, index) => { const Icon = step.icon; return <motion.div key={step.number} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.05 }} transition={{ duration: 0.55, delay: index * 0.14, ease: "easeOut" }} className={`relative z-10 pb-8 sm:pb-10 ${index === steps.length - 1 ? "pb-0" : ""}`}><span className="absolute -left-[42px] top-0 flex h-7 w-7 items-center justify-center rounded-full border border-[#347fa7] bg-[#dcecf4] font-heading text-[10px] text-[#347fa7] sm:-left-[50px] md:-left-[58px]">{step.number}</span><div className="grid gap-4 border-b border-[#abcbd9] pb-8 sm:grid-cols-[1fr_auto] sm:items-start sm:gap-6 sm:pb-9"><div><h3 className="font-heading text-2xl font-medium sm:text-3xl">{step.title}</h3><p className="mt-3 max-w-lg text-sm leading-6 text-[#526a6b]">{step.text}</p></div><Icon className="h-6 w-6 text-[#347fa7]/70 sm:mt-1" /></div></motion.div>; })}</div></div></div></section>

    <section id="lab-test" className="bg-[#f2f0e9] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="section-kicker">04 / Bukti kualitas</p><h2 className="mt-5 max-w-sm font-heading text-5xl font-medium leading-tight tracking-[-.05em]">Kualitas bisa diperiksa.</h2><p className="mt-6 max-w-sm text-sm leading-6 text-[#69716b]">Kami tunjukkan hasil uji lab supaya Anda bisa memilih dengan tenang.</p></div><div className="grid grid-cols-2 items-start gap-4 pt-4 md:gap-8">{["/tes1.jpeg", "/tes2.jpeg"].map((image, index) => <button key={image} onClick={() => setSelectedImage(image)} className={`group relative aspect-[3/4] overflow-hidden rounded-[2px] bg-white p-3 text-left shadow-[12px_16px_0_#d9d8cf] ${index === 1 ? "mt-16" : "-rotate-2"}`}><Image src={image} alt={`Dokumen uji lab ${index + 1}`} fill className="object-contain p-2 transition-transform duration-500 group-hover:scale-[1.03]" sizes="(max-width: 768px) 50vw, 35vw" /><span className="absolute bottom-4 left-4 bg-[#1b211e] px-3 py-2 text-[10px] font-bold uppercase tracking-widest text-white">Buka dokumen ↗</span></button>)}</div></div></div></section>

    <section id="delivery" className="bg-[#dcecf4] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-14 lg:grid-cols-[.85fr_1.15fr] lg:gap-24"><div><p className="section-kicker">05 / Area pengantaran</p><h2 className="mt-5 max-w-lg font-heading text-5xl font-medium leading-[.98] tracking-[-.05em] md:text-7xl">Dingin sampai<br />ke tempat Anda.</h2><p className="mt-7 max-w-md text-base leading-7 text-[#4d5b4c]">Kami melayani kebutuhan rutin kafe, restoran, hotel, dan acara di Bali. Kirim lokasi dan kebutuhan Anda, kami bantu atur.</p><Link href={whatsapp} target="_blank" className="mt-10 inline-flex items-center gap-3 rounded-full bg-[#1b211e] px-6 py-4 text-sm font-bold text-white transition-transform hover:-translate-y-1">Tanya pengiriman <ExternalLink className="h-4 w-4 text-[#8bd7ff]" /></Link></div><div className="border-t border-[#abcbd9] pt-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#347fa7]">Kami melayani</p><div className="mt-8 grid grid-cols-2 gap-x-8 sm:grid-cols-3">{["Denpasar", "Canggu", "Seminyak", "Kerobokan", "Tanah Lot", "Jimbaran", "Uluwatu"].map((area, index) => <div key={area} className="flex items-center gap-3 border-b border-[#abcbd9] py-4 text-sm font-semibold text-[#2c4b58]"><span className="font-heading text-xs text-[#66aac8]">0{index + 1}</span>{area}</div>)}</div><div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3"><Metric value="7" label="area layanan" /><Metric value="07–19" label="buka tiap hari" /><Metric value="1" label="kontak pemesanan" /></div></div></div></div></section>

    <section className="bg-[#f2f0e9] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><div className="flex flex-col items-start justify-between gap-8 border-b border-[#c9c8bf] pb-10 md:flex-row md:items-end"><div><p className="section-kicker">06 / Kata mereka</p><h2 className="mt-5 font-heading text-5xl font-medium tracking-[-.05em] md:text-7xl">Dipakai setiap hari.<br />Dipercaya terus.</h2></div><p className="max-w-xs text-sm leading-6 text-[#69716b]">Layanan yang konsisten dimulai dari partner yang bisa diandalkan.</p></div><div className="mt-12"><GoogleReviews /></div></div></section>

    <AnimatePresence>{selectedImage && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelectedImage(null)} className="fixed inset-0 z-[100] flex items-center justify-center bg-[#1b211e]/90 p-5 backdrop-blur-md"><button onClick={() => setSelectedImage(null)} className="absolute right-5 top-5 rounded-full border border-white/20 p-3 text-white"><X className="h-5 w-5" /></button><motion.div initial={{ scale: .92 }} animate={{ scale: 1 }} className="relative max-h-[90vh] max-w-[90vw] overflow-hidden bg-white p-2" onClick={(event) => event.stopPropagation()}><img src={selectedImage} alt="Detail dokumen uji lab" className="max-h-[86vh] w-auto object-contain" /></motion.div></motion.div>}</AnimatePresence>
  </div>;
}

function Info({ icon: Icon, title, text }: { icon: typeof Droplets; title: string; text: string }) { return <div><Icon className="mb-5 h-6 w-6 text-[#347fa7]" /><h3 className="font-heading text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[#69716b]">{text}</p></div>; }
function Metric({ value, label }: { value: string; label: string }) { return <div className="border-l-2 border-[#66aac8] pl-4"><strong className="block font-heading text-2xl text-[#1b211e]">{value}</strong><span className="text-xs text-[#55717c]">{label}</span></div>; }
function ProductCard({ title, eyebrow, description, tone }: { title: string; eyebrow: string; description: string; tone: "light" | "dark" }) {
  const isDark = tone === "dark";
  return <motion.article variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-80px" }} className={`group relative min-h-[520px] overflow-hidden p-8 md:p-12 ${isDark ? "bg-[#1b211e] text-[#f2f0e9] lg:mt-16" : "bg-[#f7f6f0] text-[#1b211e]"}`}><div className={`absolute right-[-12%] top-[12%] h-72 w-72 rounded-full border ${isDark ? "border-[#8bd7ff]/30" : "border-[#8fb6ca]"}`} /><div className={`absolute right-[8%] top-[28%] h-52 w-52 rounded-full border ${isDark ? "border-white/20" : "border-[#8fb6ca]"}`} /><div className="relative z-10 flex h-full min-h-[440px] flex-col justify-between"><div><p className={`text-[10px] font-bold uppercase tracking-[.22em] ${isDark ? "text-[#8bd7ff]" : "text-[#347fa7]"}`}>{eyebrow}</p><h3 className="mt-6 font-heading text-5xl font-medium tracking-[-.06em] md:text-6xl">{title}</h3><p className={`mt-6 max-w-sm text-sm leading-6 ${isDark ? "text-white/55" : "text-[#69716b]"}`}>{description}</p></div><div className="flex items-end justify-between"><div className={`flex gap-2 text-xs ${isDark ? "text-white/60" : "text-[#69716b]"}`}><span className="border border-current px-3 py-2">5 kg</span><span className="border border-current px-3 py-2">10 kg</span><span className="border border-current px-3 py-2">20 kg</span></div><Link href={whatsapp} target="_blank" aria-label={`Pesan ${title}`} className={`flex h-12 w-12 items-center justify-center rounded-full transition-transform group-hover:-translate-y-1 ${isDark ? "bg-[#8bd7ff] text-[#14202a]" : "bg-[#1b211e] text-white"}`}><ArrowUpRight className="h-5 w-5" /></Link></div></div></motion.article>;
}
